theme: jekyll-theme-cayman
title: Power BI and Azure Data Platform
description: Power BI design, DAX patterns, Power Query, M, Data Models, Azure Data Analytics
# tagline: A short description used as part of the title tag of the home page like 'title | tagline'.
google_analytics: UA-47157029-2
url: "https://beyondpowerbi.com" # the base hostname & protocol for your site
lang: en-GB # default is en-US or just en
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: Tom Fox
  links:
    - https://www.linkedin.com/in/tomfox247/
