theme: jekyll-theme-cayman
title: Power BI and Azure Synapse Analytics references
description: Power BI samples, DAX patterns, data models, Azure Data Analytics, etc.
# tagline: A short description used as part of the title tag of the home page like 'title | tagline'.
google_analytics: UA-47157029-2
url: "https://beyondpowerbi.com" # the base hostname & protocol for your site
lang: en_GB # default is en_US
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
social:
  name: Tom Fox
  links:
    - https://www.linkedin.com/in/tomfox247/
